### ISSUE TITLE
Undisclosed substance name appears in the builder

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#11]
In the builder, confidential substance were entered (example: Palmex HPD).  The name of the substanes were changedto make shure even Palmex does not see them.
![image](https://user-images.githubusercontent.com/107648303/175038968-51a72e2d-4ffa-4be7-b3cf-f2648874714d.png)

In the stage builder, the name of the confidential substance appear 'undisclosed in the list": 
![image](https://user-images.githubusercontent.com/107648303/175038592-9e8ad133-560f-4f04-b3d1-2afbf744e062.png)

However, and this is a MAJOR problem when you edit the substance, you can see the Substance Name.  Also, in the edit substance window, the box for "I do not want to disclose this substance's CAS RN #" was not checked.
![image](https://user-images.githubusercontent.com/107648303/175039653-a4f1e2d1-ae2d-4760-be06-ad74fc638b80.png)

**Comment by Millali** [comment]
Hi @ChantalLavigne, 

Thanks. Perfectly understand the issue here. 

When the checkbox for not disclosing the CAS number is checked, the users can't uncheck it and the data is protected. I tested this functionality with old and new records and is working, however, I am not sure why these substances have the box unchecked. Would you happen to have another example we could test?

Thank you!

Milla

**Comment by ChantalLavigne** [comment]
HI @Millali 

will do once I can upgrade the other two client accounts.

**Comment by Millali** [comment]
Hi Chantal, @ChantalLavigne 

What the the names of the other two clients?
Thanks!

**Comment by secondmanveran** [comment]
I believe this is resolved
